import Head from "next/head";
import {BsFillMoonStarsFill} from "react-icons/bs";
import Link from 'next/link'

export default function Home() {
  return (
    <div> 
      <Head>
        <title> Mokita portafolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between"> 
            <h1 className="text-2xl font-burtons">developedbyjess</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
              </li>
              <li className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 hover:text-gray-800" 
              href="home"> <Link href="/">Home</Link>
              </li>
            </ul>
          </nav>
          <div class="h-100 w-full flex items-center justify-center bg-teal-lightest font-sans">

	<div class="bg-white rounded shadow p-6 m-4 w-full lg:w-3/4 lg:max-w-lg">
        <div class="mb-4">
            <h1 class="text-grey-darkest">To do List</h1>
            <div class="flex mt-4">
            <div class="flex items-center mb-4">
             <input id="checkbox1" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"></input>
                <label for="Darme los buenos días" class="flex-no-shrink p-2 ml-4 mr-2 border-2 rounded hover:text-white text-green border-green hover:bg-green">Default checkbox</label>
            </div>
            </div>
        </div>
        <div>
            <div class="flex mb-4 items-center">
                <p class="w-full text-grey-darkest">Darme los buenos días</p>
                <button class="flex-no-shrink p-2 ml-4 mr-2 border-2 rounded hover:text-white text-green border-green hover:bg-green">Done</button>
                <button class="flex-no-shrink p-2 ml-2 border-2 rounded text-red border-red hover:text-white hover:bg-red">Remove</button>
            </div>
          	<div class="flex mb-4 items-center">
                <p class="w-full text-green">Servirme de desayunar</p>
                <button class="flex-no-shrink p-2 ml-4 mr-2 border-2 rounded hover:text-white text-green border-green hover:bg-green">Done</button>
                <button class="flex-no-shrink p-2 ml-2 border-2 rounded text-red border-red hover:text-white hover:bg-red">Remove</button>
            </div>
            <div class="flex mb-4 items-center">
                <p class="w-full text-green">Sacarme a pasear</p>
                <button class="flex-no-shrink p-2 ml-4 mr-2 border-2 rounded hover:text-white text-green border-green hover:bg-green">Done</button>
                <button class="flex-no-shrink p-2 ml-2 border-2 rounded text-red border-red hover:text-white hover:bg-red">Remove</button>
            </div>
            <div class="flex mb-4 items-center">
                <p class="w-full text-green">Rascarme panzota</p>
                <button class="flex-no-shrink p-2 ml-4 mr-2 border-2 rounded hover:text-white text-grey border-grey hover:bg-grey">Done</button>
                <button class="flex-no-shrink p-2 ml-2 border-2 rounded text-red border-red hover:text-white hover:bg-red">Remove</button>
            </div>
        </div>
    </div>
</div>
        </section>
        
      </main>
      <div class="p-10 bg-gray-200 text-gray-900 flex justify-between">
      <h3 class="text-lg "> Unete para más noticias </h3>
      <form class="flex"> 
      <input type="email" class="w-full rounded"></input>
      <button class="bg-gradient-to-r from-cyan-500 to-teal-500 text-white rounded px-4 py-3">Unete</button>
  </form>
  <div>
  Copyright & copy: Jessica 2023- Infinito
  </div>
</div>
    </div>
  );
} 









































      