import Head from "next/head";
import {BsFillMoonStarsFill} from "react-icons/bs";
import Image from "next/image";
import mokis from '../public/mokis.JPG';
import Link from 'next/link'

export default function Home() {
  return (
    <div> 
      <Head>
        <title> Mokita portafolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between"> 
            <h1 className="text-2xl font-burtons">developedbyjess</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
              </li>
              <li className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 hover:text-gray-80" 
              href="conoce"> <Link href="/conoce">Conoce más</Link>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600"> Mokita Gonzalez</h2>
            <h3 className="text-2xl py-2"> Perre y amigue</h3>
            <p className= "text-md py-5 leading-8 text-gray-800"> 
              Soy un perro de dudosa procedencia. Tengo 5 años. Tengo varios hermanes, y 
              los bulleo a todos, pero el que me bullea a mi se llama Robertito. Es un Husky
              que ladra como si estuviera pariendo. 
            </p>
          </div>
          <div className="mx-auto relative object-contain h-100 w-80 "> 
            <Image src={mokis}/>
          </div> 
        </section>
        <section> 
          <h3 className="text-3xl py-3"> 
            Servicios
          </h3>
          <p className="text-md py-2 leading-8  text-gray-800"> 
          Desde que nací he sido muy <span className="text-teal-500"> bonita</span> y <span className="text-teal-500"> amorosa </span>. 
          He estado en la familia por más de un lustro. 
          </p>
          
<div class="py-5 mx-auto w-full max-w-md p-4 bg-white border rounded-lg shadow-md sm:p-8 dark:bg-gray-800 dark:border-gray-700">
    <div class="flex items-center justify-between mb-4">
        <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white">Servicios que ofrezco</h5>
        <a href="#" class="text-sm font-medium text-teal-600 hover:underline dark:text-teal-500">
            View all
        </a>
   </div>
   <div class="flow-root">
        <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
            <li class="py-3 sm:py-4">
                <div class="flex items-center space-x-4">
                    <div class="flex-1 min-w-0">
                        <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
                            Salir a Pasear
                        </p>
                        <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                            Puede ser a la placita, a un parque o en el carro.
                        </p>
                    </div>
                    <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                        $320
                    </div>
                </div>
            </li>
            <li class="py-3 sm:py-4">
                <div class="flex items-center space-x-4">
                    <div class="flex-1 min-w-0">
                        <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
                            Darme de comer
                        </p>
                        <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                            Como de todo, no vas a batallar.
                        </p>
                    </div>
                    <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                        $0
                    </div>
                </div>
            </li>
            <li class="py-3 sm:py-4">
                <div class="flex items-center space-x-4">
                    <div class="flex-1 min-w-0">
                        <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
                            Rascar panza
                        </p>
                        <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                            Tienes que tocar mi hermoso pelaje
                        </p>
                    </div>
                    <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                        $67
                    </div>
                </div>
            </li>
            <li class="py-3 sm:py-4">
                <div class="flex items-center space-x-4">
                    <div class="flex-1 min-w-0">
                        <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
                            Romper cosas que no quieres
                        </p>
                        <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                            Mis dientes estan hechos del metal mas duro.
                        </p>
                    </div>
                    <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                        $367
                    </div>
                </div>
            </li>
        </ul>
   </div>
</div>

        
        </section>
        
      </main>
      <div class="p-10 bg-gray-200 text-gray-900 flex justify-between">
      <h3 class="text-lg "> Unete para más noticias </h3>
      <form class="flex"> 
      <input type="email" class="w-full rounded"></input>
      <button class="bg-gradient-to-r from-cyan-500 to-teal-500 text-white rounded px-4 py-3">Unete</button>
  </form>
  <div>
  Copyright & copy: Jessica 2023- Infinito
  </div>
</div>
    </div>
  );
} 
